---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/follows/follow":
    post:
      summary: follow a user
      tags:
      - Follows
      parameters: []
      responses:
        '200':
          description: follow successful
        '404':
          description: resource not found
        '422':
          description: 'invalid request: cannot follow yourself'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                follow:
                  type: object
                  schema:
                    follower_id:
                      type: string
                    followed_id:
                      type: string
  "/api/v1/follows/unfollow":
    delete:
      summary: follow a user
      tags:
      - Follows
      parameters: []
      responses:
        '204':
          description: unfollow successful
        '404':
          description: resource not found
        '422':
          description: 'invalid request: cannot follow yourself'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                follow:
                  type: object
                  schema:
                    follower_id:
                      type: string
                    followed_id:
                      type: string
  "/api/v1/users/{user_id}/newsfeeds":
    get:
      summary: retrieve newsfeed for a user
      tags:
      - Newsfeeds
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: newsfeed retrieved
        '404':
          description: resource not found
  "/api/v1/users/{user_id}/sleep_logs":
    post:
      summary: create a sleep log for a user
      tags:
      - Sleep Logs
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: sleep log created
        '404':
          description: resource not found
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sleep_log:
                  type: object
                  schema:
                    user_id:
                      type: string
                    clock_in:
                      type: string
  "/api/v1/users/{user_id}/sleep_logs/{id}":
    put:
      summary: update a sleep log
      tags:
      - Sleep logs
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: sleep log created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sleep_log:
                  type: object
                  schema:
                    user_id:
                      type: string
                    clock_in:
                      type: string
                    clock_out:
                      type: string
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
